#!/bin/bash

#catch errors
set -euo pipefail

echo "### Updating CachyOS..."
echo

#update pacman and yay, default response to questions
yay -Syu --noconfirm

#update flatpak apps
flatpak update -y

echo
echo "### Updating GPU drivers..."
echo

sudo chwd --autoconfigure || true

echo
echo "### Removing unused packages"
echo

sudo paccache -rk3
yay -Sc --aur --noconfirm

echo
echo "### All updates complete!"
